### ISSUE TITLE
https://kontist.dev Seite – Kein SSL-Zertifikat

### ISSUE THREAD

**Issue by elnicknamio** [kontist/kontist.github.io#51]
Aktuell kommt man leider nicht auf eure GraphQL-Dokumentation, weil das SSL-Zertifikat anscheinend ausgelaufen ist.

**Comment by johannespfeiffer** [comment]
Wo genau? Kann ich gerade nicht nachvollziehen:

```
echo | openssl s_client -servername kontist.dev -connect kontist.dev:443 2>/dev/null | openssl x509 -noout -dates

notBefore=Feb  5 10:33:20 2020 GMT
notAfter=May  5 10:33:20 2020 GMT
```

<img width="488" alt="Bildschirmfoto 2020-02-24 um 08 36 39" src="https://user-images.githubusercontent.com/6780316/75156830-f0c00300-56e0-11ea-99c7-dc09df91e74e.png">

**Comment by elnicknamio** [comment]
Sorry, hat mit meiner Laravel Valet Konfiguration zutun, weil ich dort .dev-Domains als Testumgebung nutze. Mein Fehler. 😅

**Comment by johannespfeiffer** [comment]
Alles klar 😄 dann kann ich dieses Ticket schließen. Falls noch etwas ist einfach melden.
