### ISSUE TITLE
400 - Invalid payload: client

### ISSUE THREAD

**Issue by Barny-Blog** [kontist/kontist.github.io#56]
Hallo!

Bei dem Versuch mein Kontist-Konto mittels API zu erreichen stellte ich heute bei der Authentifizierung nachfolgenden Fehler fest:
1. Aufruf von 
> https://api.kontist.com/api/oauth/authorize?scope=offline&response_type=code&client_id={Client ID meiner zuvor erstellten Anwendung}&redirect_uri=https://meine-domain.tld/callback.php&state=OPAQUE_VALUE

im Browser.

2. Authentifizierung mittels Anmeldedaten inkl. Bestätigung der Anmeldung in der Kontist-App. Ergebnis:
> {
  "status": 400,
  "type": "http://www.iana.org/assignments/http-status-codes#400",
  "title": "Invalid payload: client"
}

Verweigere ich jedoch den Zugriff der Anwendung, so werde ich korrekt zu meiner Application weitergeleitet und kann die GET-Parameter "state" und "error" auslesen und verarbeiten. Die "callback.php" enthält zu Testzwecken nur eine Ausgabe der GET-Parameter.

Mache ich etwas falsch oder habe ich etwas übersehen? Für meinen Test habe ich Mozilla Firefox und Microsoft Edge verwendet.

Vielen Dank für die Unterstützung!

**Comment by johannespfeiffer** [comment]
Hallo,
wie genau sieht der POST-Call zu `/api/oauth/authorize` aus?

Dort müssen noch mal die gleichen Daten wie unter 1. übertragen werden - zusätzlich zu dem `code`.

```
curl https://api.kontist.com/api/oauth/token \
  -X POST \
  -H 'content-type: application/x-www-form-urlencoded' \
  -d grant_type=authorization_code \
  -d code=59f53e7cfcf12f1d36e2fb56bb46b8d116fb8406 \
  -d client_id={Client ID meiner zuvor erstellten Anwendung} \
  -d client_secret=my-secret \
  -d scope=offline \
  -d redirect_uri=https://meine-domain.tld/callback.php
```

**Comment by johannespfeiffer** [comment]
Hi,

kann es sein, dass das Request ein doppeltes Fragezeichen enthielt, also z.B. so
```
https://api.kontist.com/api/oauth/authorize?scope=offline&...&redirect_uri=...callback.php?state=OPAQUE_VALUE
```

Unsere Logs deuten darauf hin.

**Comment by johannespfeiffer** [comment]
Anstatt `?state=OPAQUE_VALUE` sollte es also `&state=OPAQUE_VALUE` heißen.

**Comment by Barny-Blog** [comment]
Hallo,

du hast natürlich vollkommen recht! Ich habe das Zeichen wohl von den ersten Testaufrufen meiner Anwendung mitkopiert... Danke für die Hilfe!
