### ISSUE TITLE
Test Account

### ISSUE THREAD

**Issue by saschaklatt** [kontist/kontist.github.io#61]
Hi, I'd like to play around with the Kontist API but I don't want to mess with my real account. Would it instead be possible to get some kind of testing/dummy account for development purposes?

**Comment by johannespfeiffer** [comment]
Hi @klattiation,

Thank you for your interest in our API.
Currently, we do not offer public access to a separate testing environment. And it is not possible to create test accounts on production (as they would need to be connected with a real bank account then).

Best,
Joe
